# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15e1ef04486d8e969ac2da009b55ccd9ec57d27ad99ebaad068359f96f8a18d77817dcbf6680049e7f7a523fc6d4e6dd60dde0452505458daf80a78bd390303e
  HEROKU_KEY: Bearer 05094439-e12b-4997-bf7f-eb6f44bb1d5f
test:
  secret_key_base: d65bb0ba578ee0a9563d1c415108f167d1b356e173d983996b3f306b6515ebec6329e3e1fd3e6451a4afa6cff61f65050ac070f2be8cfc5f5d14660f761c05fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  HEROKU_KEY: <%= ENV["HEROKU_KEY"] %>
